---
name: Time-Fuzzy
version: 0.36
author:
  - 'Jerome Quelin <jquelin@cpan.org>'
abstract: 'Time read like a human, with some fuzziness'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor: 0
  DateTime: 0
build_requires:
  Class::Accessor: 0
  DateTime: 0
  Test::More: 0
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Time::Fuzzy:
    file: lib/Time/Fuzzy.pm
    version: 0.36
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
